import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { SKILL_DIR } from "./paths.js";
import { buildCapabilityManifest, type CapabilityManifest } from "./capability.js";
import type { OptionSpec } from "./registry.js";

/**
 * Steering-layer generator (`acm agent-docs`, ADR 0004): projects the
 * capability manifest into the Discovery Skill's Generated Blocks and merges
 * them with the Authored Blocks in `packages/discovery-skill/blocks/` into
 * per-ecosystem targets. Outputs are generated artifacts (invariant #1):
 * regenerated by `pnpm generate`, checked by `pnpm drift`, never hand-edited.
 *
 * The generator is corpus-agnostic by design rule: it runs at build time,
 * never touches a Manifest Corpus, and never inlines component data — the
 * skill teaches retrieval, so hostile Manifest text cannot ride into resident
 * context via generation (architecture doc §8).
 */

export const SKILL_PACKAGE_DIR = SKILL_DIR;
const BLOCKS_DIR = path.join(SKILL_PACKAGE_DIR, "blocks");

export const AUTHORED_BLOCK_IDS = [
  "activation",
  "corpus-preamble",
  "workflow",
  "error-playbook",
  "security-posture",
  "runtime-truth",
] as const;

export const GENERATED_BLOCK_IDS = [
  "quick-reference",
  "option-tables",
  "examples",
  "error-codes",
  "response-types",
] as const;

/** Body order shared by every target (architecture doc §6). */
export const BODY_BLOCK_ORDER = [
  "corpus-preamble",
  "workflow",
  "quick-reference",
  "option-tables",
  "examples",
  "error-codes",
  "error-playbook",
  "response-types",
  "security-posture",
  "runtime-truth",
] as const;

export type BlockId = (typeof AUTHORED_BLOCK_IDS)[number] | (typeof GENERATED_BLOCK_IDS)[number];

const DO_NOT_EDIT =
  "<!-- Generated by `acm agent-docs` from the acm capability manifest — do not edit by hand. Regenerate with `pnpm generate`; staleness fails CI. -->";

function wrapBlock(id: string, content: string): string {
  return `<!-- acm:block ${id} -->\n${content.trim()}\n<!-- /acm:block ${id} -->`;
}

/** Extract `<!-- acm:block id -->…<!-- /acm:block id -->` regions from a target. */
export function extractBlocks(target: string): Map<string, string> {
  const blocks = new Map<string, string>();
  const pattern = /<!-- acm:block ([a-z-]+) -->\n([\s\S]*?)\n<!-- \/acm:block \1 -->/g;
  for (const match of target.matchAll(pattern)) blocks.set(match[1]!, match[2]!);
  return blocks;
}

function usage(command: CapabilityManifest["commands"][number]): string {
  const args = command.arguments
    .map((a) => {
      const label = a.variadic === true ? `${a.name}…` : a.name;
      return a.required ? ` <${label}>` : ` [${label}]`;
    })
    .join("");
  return `acm ${command.name}${args}`;
}

function optionRows(options: OptionSpec[]): string[] {
  return options.map((option) => {
    const dflt = option.default !== undefined ? `\`${String(option.default)}\`` : "—";
    const type = option.type === "enum" ? (option.choices ?? []).join(" \\| ") : option.type;
    return `| \`${option.flag}\` | ${type} | ${dflt} | ${option.description} |`;
  });
}

/** The discovery subset: exactly the commands in `jsonSupported` (decision D1). */
function discoveryCommands(cap: CapabilityManifest): CapabilityManifest["commands"] {
  return cap.commands.filter((c) => cap.jsonSupported.includes(c.name));
}

export function renderGeneratedBlocks(cap: CapabilityManifest): Record<string, string> {
  const commands = discoveryCommands(cap);

  const quickReference = [
    "## Command quick reference",
    "",
    "| Command | Purpose |",
    "| --- | --- |",
    ...commands.map((c) => `| \`${usage(c)} --json\` | ${c.description} |`),
  ].join("\n");

  const discoveryNames = commands.map((c) => c.name);
  const sharedGlobals = cap.globalOptions.filter((g) =>
    g.appliesTo.some((name) => discoveryNames.includes(name)),
  );
  const optionTables = [
    "## Options",
    "",
    "Shared options (the `appliesTo` commands):",
    "",
    "| Option | Applies to | Type | Default | Meaning |",
    "| --- | --- | --- | --- | --- |",
    ...sharedGlobals.map((option) => {
      const dflt = option.default !== undefined ? `\`${String(option.default)}\`` : "—";
      const type = option.type === "enum" ? (option.choices ?? []).join(" \\| ") : option.type;
      return `| \`${option.flag}\` | ${option.appliesTo.join(", ")} | ${type} | ${dflt} | ${option.description} |`;
    }),
    "",
    ...commands.flatMap((c) => {
      if (c.options.length === 0) return [];
      return [
        `### \`acm ${c.name}\``,
        "",
        "| Option | Type | Default | Meaning |",
        "| --- | --- | --- | --- |",
        ...optionRows(c.options),
        "",
      ];
    }),
  ]
    .join("\n")
    .trimEnd();

  const examples = ["## Examples", "", ...commands.map((c) => `- \`${c.examples[0]!}\``)].join(
    "\n",
  );

  const errorCodes = [
    "## Error codes",
    "",
    "| Code | Meaning |",
    "| --- | --- |",
    ...cap.errorCodes.map((e) => `| \`${e.code}\` | ${e.description} |`),
  ].join("\n");

  const responseTypes = [
    "## Response types",
    "",
    ...commands.map(
      (c) => `- \`acm ${c.name}\` → ${c.responseTypes.map((t) => `\`${t}\``).join(", ")}`,
    ),
  ].join("\n");

  return {
    "quick-reference": quickReference,
    "option-tables": optionTables,
    examples,
    "error-codes": errorCodes,
    "response-types": responseTypes,
  };
}

export function readAuthoredBlocks(): Record<string, string> {
  const blocks: Record<string, string> = {};
  for (const id of AUTHORED_BLOCK_IDS) {
    blocks[id] = readFileSync(path.join(BLOCKS_DIR, `${id}.md`), "utf8");
  }
  return blocks;
}

function assembleBody(blocks: Record<string, string>): string {
  return BODY_BLOCK_ORDER.map((id) => wrapBlock(id, blocks[id]!)).join("\n\n");
}

/** The activation description as the single-line skill frontmatter value. */
function activationLine(blocks: Record<string, string>): string {
  return blocks.activation!.trim().replace(/\s*\n\s*/g, " ");
}

export interface SkillFiles {
  /** REPO_ROOT-relative path → content, for drift and --write. */
  files: Array<[string, string]>;
  /** Target name (for `--target`) → REPO_ROOT-relative path of its main file. */
  targets: Record<string, string>;
}

export function buildSkillFiles(cap: CapabilityManifest = buildCapabilityManifest()): SkillFiles {
  const blocks = { ...readAuthoredBlocks(), ...renderGeneratedBlocks(cap) };
  const body = assembleBody(blocks);

  const skillMd = [
    "---",
    "name: acm-discovery",
    `description: ${activationLine(blocks)}`,
    "---",
    "",
    DO_NOT_EDIT,
    "",
    body,
    "",
  ].join("\n");

  const agentsFragment = ["# ACM component discovery", "", DO_NOT_EDIT, "", body, ""].join("\n");

  const rulesFile = [DO_NOT_EDIT, "", body, ""].join("\n");

  const rel = (p: string): string => path.join("packages/discovery-skill/generated", p);
  const files: Array<[string, string]> = [
    ...GENERATED_BLOCK_IDS.map((id): [string, string] => [
      rel(`blocks/${id}.md`),
      renderGeneratedBlocks(cap)[id]! + "\n",
    ]),
    [rel("targets/claude-skill/acm-discovery/SKILL.md"), skillMd],
    [rel("targets/skills-package/acm-discovery/SKILL.md"), skillMd],
    [rel("targets/AGENTS.fragment.md"), agentsFragment],
    [rel("targets/rules/acm-discovery.md"), rulesFile],
  ];
  return {
    files,
    targets: {
      "claude-skill": rel("targets/claude-skill/acm-discovery/SKILL.md"),
      "skills-package": rel("targets/skills-package/acm-discovery/SKILL.md"),
      "agents-md": rel("targets/AGENTS.fragment.md"),
      rules: rel("targets/rules/acm-discovery.md"),
    },
  };
}

export const SKILL_TARGET_NAMES = ["claude-skill", "skills-package", "agents-md", "rules"] as const;

/**
 * The authored-block reference gate (spec 005 FR-005, decision D5): sweep ALL
 * authored text — backticked or not — for distinctively-shaped surface tokens
 * and verify each against the capability manifest. Returns human-readable
 * problems; empty means the gate passes.
 */
export function sweepAuthoredReferences(
  blocks: Record<string, string>,
  cap: CapabilityManifest = buildCapabilityManifest(),
): string[] {
  const problems: string[] = [];
  const commandNames = new Set(cap.commands.map((c) => c.name));
  const flags = new Set<string>();
  for (const option of [...cap.globalOptions, ...cap.commands.flatMap((c) => c.options)]) {
    const name = /^--([a-z][a-z-]*)/.exec(option.flag);
    if (name) flags.add(`--${name[1]!}`);
  }
  const codes = new Set(cap.errorCodes.map((e) => e.code));
  const responseTypes = new Set<string>(Object.values(cap.responseTypes).flat());

  for (const [id, text] of Object.entries(blocks)) {
    // `acm <word>` invocations (not inside @acm/… package names or paths).
    for (const match of text.matchAll(/(?<![@\w/-])acm ([a-z][a-z-]*)/g)) {
      if (!commandNames.has(match[1]!))
        problems.push(`${id}: references nonexistent command "acm ${match[1]!}"`);
    }
    // --flag tokens.
    for (const match of text.matchAll(/(?<![\w-])--[a-z][a-z-]*/g)) {
      if (!flags.has(match[0]!))
        problems.push(`${id}: references nonexistent option "${match[0]!}"`);
    }
    // ACM-D-* codes.
    for (const match of text.matchAll(/ACM-D-[A-Z][A-Z-]*/g)) {
      if (!codes.has(match[0]!)) problems.push(`${id}: references nonexistent code "${match[0]!}"`);
    }
    // Dot-namespaced response types rooted in a command name.
    for (const match of text.matchAll(/\b(?:search|component|capabilities)\.[a-z][a-z.]*\b/g)) {
      if (!responseTypes.has(match[0]!))
        problems.push(`${id}: references nonexistent response type "${match[0]!}"`);
    }
  }
  return problems;
}

/** Guard against a body-order or blocks-directory drift: every file must be a known block. */
export function checkBlockInventory(): string[] {
  const problems: string[] = [];
  const present = new Set(
    readdirSync(BLOCKS_DIR)
      .filter((f) => f.endsWith(".md"))
      .map((f) => f.slice(0, -3)),
  );
  for (const id of AUTHORED_BLOCK_IDS)
    if (!present.has(id)) problems.push(`missing authored block: ${id}.md`);
  for (const file of present)
    if (!(AUTHORED_BLOCK_IDS as readonly string[]).includes(file))
      problems.push(`unexpected file in blocks/: ${file}.md`);
  return problems;
}
